---
sudo: required
dist: trusty
language: node_js
node_js:
  # LTS version
  - "8.0"
cache:
  directories:
    - node_modules
install:
  - yarn install
before_script:
  - export CI=false
# command to run tests
script:
    - npm test --coverage
after_success:
  coveralls
